version: "3.9"
services:
  javascript-profiler:
    image: javascript-profiler
    volumes:
      - ./:/teamscale-javascript-profiler
    command: sh -c "pnpm install && pnpm build && node ./test/systemtest.mjs release"
