[package]
name = "teamscale-istanbul-postprocessor-swc-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
serde = "1"
swc_common = "0.26.0"
swc-coverage-instrument = "*"
swc_ecmascript = { version = "0.188.1", features = ["utils", "visit"] }
swc_plugin = { version = "0.89.0" }
swc_ecma_quote = "0.32.1"
swc_ecma_ast = "0.90.4"
tracing-subscriber = { version = "0.3.15", features = ["fmt"] }
swc_ecma_visit="0.76.2"
swc_core = {version = "0.6.5", features = [
  "plugin_transform",
  "utils",
  "visit",
  "ast",
  "common",
]}

[dev-dependencies]
swc_ecma_transforms_testing="0.105.1"
swc_ecmascript = { version = "0.188.1", features = ["parser", "transforms"] }
swc_ecma_parser="0.117.1"
swc_ecma_ast="0.90.4"
testing="*"
