[package]
name = "teamscale-istanbul-postprocessor-swc-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1"
swc_common = "0.26.0"
swc-coverage-instrument = "*"
swc_plugin = { version = "0.71.0" }

[dev-dependencies]
swc_ecma_transforms_testing="0.96.0"
swc_ecma_parser="0.108.1"
swc_ecma_visit="0.67.1"
swc_ecma_ast="0.81.0"
testing="*"
