[package]
name = "teamscale-istanbul-postprocessor-swc-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
serde = "1"
swc_common = "0.27.15"
swc-coverage-instrument = { version = "0.0.12" }
swc_ecmascript = { version = "0.198.10", features = ["utils", "visit"] }
swc_ecma_quote = "0.34.2"
tracing-subscriber = { version = "0.3.15", features = ["fmt"] }
swc_core = {version = "0.20.12", features = [
  "plugin_transform",
  "common",
  "ecma_ast",
  "ecma_utils",
  "ecma_visit",
  "ecma_parser",
  "ecma_transforms",
]}

[dev-dependencies]
testing = "0.29.4"
swc_core = { version = "0.20.12", features = [
  "ecma_parser",
  "ecma_transforms",
  "testing_transform"
] }