[package]
description = "SWC instrumentation plugin to be used by the Teamscale JavaScript Profiler"
name = "swc_plugin_teamscale_instrumenter"
version = "0.0.1-beta.42"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[profile.release]
lto = true

[dependencies]
serde = "1"
serde_json = "1"
lazy_static = "1"
swc = "0.232.1"
swc_common = "0.29.1"
swc-coverage-instrument = { version = "0.0.13" }
swc_ecmascript = { version = "0.205.1", features = ["utils", "visit"] }
swc_ecma_quote = "0.38.3"
tracing-subscriber = { version = "0.3.15", features = ["fmt"] }
swc_core = {version = "0.31.1", features = [
  "plugin_transform",
  "common",
  "ecma_ast",
  "ecma_utils",
  "ecma_visit",
  "ecma_parser",
  "ecma_transforms",
  "ecma_codegen",
]}

[dev-dependencies]
testing = "0.31.1"
swc_core = { version = "0.31.1", features = [
  "ecma_parser",
  "ecma_transforms",
  "testing_transform"
] }
