on:
  push:
    branches: '*'
    tags: 'v*'
  pull_request:
    branches: '*'

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Check out the code
        uses: actions/checkout@v2
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn workspaces foreach install
      - run: echo "Done."