on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      ENV DBUS_SESSION_BUS_ADDRESS: /dev/null
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install -g yarn
      - name: Install the base dependencies
        run: yarn install
      - name: Install, build, and test the Commons Library
        working-directory: ./packages/cqse-commons
        run: | 
          yarn install
          yarn build
          yarn test
      - name: Install, build, and test the Instrumenter
        working-directory: ./packages/teamscale-javascript-instrumenter
        run: | 
          yarn install
          yarn build
          yarn test
      - name: Install, build, and test the Collector
        working-directory: ./packages/teamscale-coverage-collector
        run: | 
          yarn install
          yarn build
          yarn test
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run the system test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn systemtest
      - run: echo "Done."

