on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build-and-test:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install -g yarn
      - name: Install the base dependencies
        run: yarn install
      - name: Install the dependencies for all workspaces
        run: yarn workspaces foreach install
      - name: Build all workspaces
        run: yarn workspaces foreach build
      - name: Run the tests for all workspaces
        run: yarn workspaces foreach test
      - name: Run the system test
        run: yarn systemtest
      - run: echo "Done."

