on:
  push:
    tags: 'v*'

jobs:
  release-node:
    name: Release the Node Package
    runs-on: ubuntu-latest
    env:
      ENV DBUS_SESSION_BUS_ADDRESS: /dev/null
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Install NodeJS in the desired version
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install -g yarn
      - name: Install the base dependencies
        run: yarn install
      - name: Install the dependencies for all workspaces
        run: yarn workspaces foreach install
      - name: Build all workspaces
        run: yarn workspaces foreach run build
      - name: Run the tests for all workspaces
        run: yarn workspaces foreach run test
      - name: Run the system test
        run: yarn systemtest
      - name: Publish the Commons Library
        working-directory: ./packages/cqse-commons
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish the Collector
        working-directory: ./packages/teamscale-coverage-collector
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish the Instrumenter
        working-directory: ./packages/teamscale-javascript-instrumenter
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  release-docker:
    name: Release the Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: cqse/teamscale-coverage-collector
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: ls
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./packages/teamscale-coverage-collector
        file: ./packages/teamscale-coverage-collector/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

